from django.db import models


# =========================================================
# 1. MOVIE
# =========================================================

class Movie(models.Model):
    movie_id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=255)
    genres = models.CharField(
        max_length=500,
        blank=True
    )

    def __str__(self):
        return self.title


# =========================================================
# 2. TAG
# =========================================================
# From tags.csv:
# userId,movieId,tag,timestamp
#
# We keep "tag" because your existing database already
# uses this field name.

class Tag(models.Model):
    tag = models.CharField(max_length=255)

    def __str__(self):
        return self.tag


# =========================================================
# 3. MOVIE TAG
# =========================================================
# Connects Movie and Tag.
#
# Movie  <---->  Tag
#
# A movie can have many tags.
# A tag can belong to many movies.

class MovieTag(models.Model):
    movie = models.ForeignKey(
        Movie,
        on_delete=models.CASCADE,
        related_name="movie_tags"
    )

    tag = models.ForeignKey(
        Tag,
        on_delete=models.CASCADE,
        related_name="movie_tags"
    )

    class Meta:
        unique_together = ("movie", "tag")

    def __str__(self):
        return f"{self.movie.title} - {self.tag.tag}"


# =========================================================
# 4. RATING
# =========================================================
# From ratings.csv:
# userId,movieId,rating,timestamp
#
# We keep "rating" because your existing database already
# uses this field name.

class Rating(models.Model):
    user_id = models.IntegerField()

    movie = models.ForeignKey(
        Movie,
        on_delete=models.CASCADE,
        related_name="ratings"
    )

    rating = models.FloatField()

    timestamp = models.BigIntegerField()

    def __str__(self):
        return (
            f"User {self.user_id} - "
            f"{self.movie.title} - "
            f"{self.rating}"
        )


# =========================================================
# 5. MOOD GENRE MAPPING
# =========================================================
#
# Example:
# Happy -> Comedy, Animation
# Sad   -> Drama
# Excited -> Action, Adventure
#
# keywords can contain:
# "funny, friendship, comedy, cheerful"

class MoodGenreMapping(models.Model):
    mood_name = models.CharField(
        max_length=100
    )

    genres = models.CharField(
        max_length=500
    )

    keywords = models.TextField(
        blank=True
    )

    def __str__(self):
        return self.mood_name


# =========================================================
# 6. MOOD HISTORY
# =========================================================
#
# Stores the moods selected by users.

class MoodHistory(models.Model):
    user_id = models.IntegerField()

    mood = models.ForeignKey(
        MoodGenreMapping,
        on_delete=models.CASCADE,
        related_name="mood_history"
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return (
            f"User {self.user_id} - "
            f"{self.mood.mood_name}"
        )


# =========================================================
# 7. MOVIE LINKS
# =========================================================
# From links.csv:
# movieId,imdbId,tmdbId

class MovieLink(models.Model):
    movie = models.OneToOneField(
        Movie,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name="link"
    )

    imdb_id = models.IntegerField(
        null=True,
        blank=True
    )

    tmdb_id = models.IntegerField(
        null=True,
        blank=True
    )

    def __str__(self):
        return (
            f"{self.movie.title} - "
            f"IMDb: {self.imdb_id}"
        )

# =========================================================
# 8. RECOMMENDATION
# =========================================================
#
# Stores the movies generated by the AI recommendation
# engine for a particular mood.
#

class Recommendation(models.Model):

    movie = models.ForeignKey(
        Movie,
        on_delete=models.CASCADE,
        related_name="recommendations"
    )

    mood = models.ForeignKey(
        MoodGenreMapping,
        on_delete=models.CASCADE,
        related_name="recommendations"
    )

    mood_similarity = models.FloatField(
        default=0
    )

    average_rating = models.FloatField(
        default=0
    )

    rating_count = models.IntegerField(
        default=0
    )

    final_score = models.FloatField(
        default=0
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return (
            f"{self.mood.mood_name} - "
            f"{self.movie.title}"
        )