# Generated by Django 4.2.30 on 2026-09-01 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_recommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-final_score']},
        ),
    ]
