# Generated by Django 6.1 on 2026-09-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0003_alter_recommendation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielink',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
