# Generated by Django 4.2.30 on 2026-08-17 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0003_remove_movie_admin_id_remove_movie_average_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodGenreMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_name', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=500)),
                ('keywords', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movielink',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='movielink',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='link', serialize=False, to='moviesapp.movie'),
        ),
        migrations.CreateModel(
            name='MoodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_history', to='moviesapp.moodgenremapping')),
            ],
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_tags', to='moviesapp.movie')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_tags', to='moviesapp.tag')),
            ],
            options={
                'unique_together': {('movie', 'tag')},
            },
        ),
    ]
