# Generated by Django 6.1 on 2026-09-06 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0004_movielink_poster_url'),
        ('moviesapp', '0004_rating_is_dataset_rating'),
    ]

    operations = [
    ]
