# Generated by Django 5.1.3 on 2026-08-11 10:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.DateTimeField()),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='MoodGenreMapping',
            fields=[
                ('mood_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mood_genre_mapping',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='movieapp_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='movieapp_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('rating_count', models.IntegerField(blank=True, default=0, null=True)),
                ('popularity', models.FloatField(blank=True, default=0.0, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('genres_id', models.IntegerField(blank=True, null=True)),
                ('genres_name', models.CharField(blank=True, max_length=100, null=True)),
                ('movies_id', models.IntegerField(blank=True, null=True)),
                ('movies_name', models.CharField(blank=True, max_length=100, null=True)),
                ('movies_description', models.CharField(blank=True, max_length=100, null=True)),
                ('movies_year', models.IntegerField(blank=True, null=True)),
                ('movies_genre', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'movies',
                'indexes': [models.Index(fields=['title'], name='movies_title_179e04_idx'), models.Index(fields=['popularity'], name='movies_popular_befb0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movieapp.movie')),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('cast', models.TextField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('production_companies', models.CharField(blank=True, max_length=255, null=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movieapp.movie')),
            ],
            options={
                'db_table': 'movie_details',
            },
        ),
        migrations.CreateModel(
            name='MoodHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('session_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.moodgenremapping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mood_history',
                'unique_together': {('user', 'mood')},
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.movie')),
            ],
            options={
                'db_table': 'movie_genres',
                'unique_together': {('movie', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratings_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_value', models.FloatField()),
                ('review', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings',
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.DateTimeField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.movie')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.tag')),
            ],
            options={
                'db_table': 'movie_tags',
                'unique_together': {('movie', 'tag')},
            },
        ),
    ]
